### ISSUE TITLE
Script Brushes: using set_height() near the edges of a chunk leads to gaps .

### ISSUE THREAD

**Issue by gratural** [wowdev/noggit3#100]
It looks like sel:verts() does not loop over vertices in neighboring chunks.
It seems to me that it would make sense if it worked with vertices of adjacent chunks too. Within the radius of the brush, of course. Like sel:tex().
By the way. These gaps can be smoothed only with the 'Flatten' tool. 'Fix gaps' doesn't fix them.

![set_height](https://user-images.githubusercontent.com/3275410/129340403-34d9440f-0ff1-4b67-bf0b-396ef9b3488e.png)

**Comment by ihm-tswow** [comment]
can you post the script where this happens? That shouldn't happen, and I cannot reproduce it

**Comment by gratural** [comment]
Yes, of course

[1_mwc_single_placer.zip](https://github.com/wowdev/noggit3/files/6981707/1_mwc_single_placer.zip)

**Comment by ihm-tswow** [comment]
~~I get no issues trying this even across adt lines on map 559 (nagrand arena), 0 (eastern kingdoms) or my own testing map generated with adtcreator and riu's zone masher (the effect is as expected, I get a small bump as it places the prop). I assume you're trying this on a custom map, can you try it on a blizzard map? It might be your chunk layout that's broken~~

**Comment by ihm-tswow** [comment]
Nevermind, I can reproduce this now (had to use a small enough brush size). I think this is really a bug with small selections: they're too big. The smallest brush size where I cannot get this to happen at all is 6.  (Thus, a temporary workaround is to use an outer brush size of at least 6, and use the inner one if you want more placement precision)

**Comment by ihm-tswow** [comment]
Nevermind, again. Your script is just a little broken: You're doing `sel:apply()` at the end, but you also need to do `sel_vert:apply()`, since it might be larger than `sel`. Fix that and it works for any sizes or erosion settings.

**Comment by gratural** [comment]
Really, I missed that one. Yes, now the second 'sel' can be made larger than the first. There are no more gaps. Thank you, Ihm!
