### ISSUE TITLE
FPS is tragically dropped in Tile mode. Linux

### ISSUE THREAD

**Issue by gratural** [wowdev/noggit3#107]
I do not understand Noggit - in tile mode fps decreases by 10-20 times!
It does not depend on the size of the window Noggit, any settings do not increase it. 
In win build (on Wine) performance drop around 50% (acceptable).

And I have a question - why is one core of CPU loaded to 100%?

Also, no it's not wayland.
I am attaching the log and screenshots.
![Screenshot_20211022_001436](https://user-images.githubusercontent.com/3275410/138358416-f45b2a1e-04d8-4af6-a916-210ceaef19d5.png)

[log.txt](https://github.com/wowdev/noggit3/files/7392840/log.txt)
![Screenshot_20211021_235953](https://user-images.githubusercontent.com/3275410/138356876-67a7b6ae-b102-4752-98d2-7ea385367423.png)
![Screenshot_20211022_000009](https://user-images.githubusercontent.com/3275410/138356906-19dd3f69-e7d1-48fe-908d-6fe537f6779c.png)

**Comment by Adspartan** [comment]
Fixed in 23a689f
