### ISSUE TITLE
pressing f9 does not render map contour info

### ISSUE THREAD

**Issue by zarkeven** [wowdev/noggit3#117]
pretty much title. The shortcut for the map contour info does not work.

**Comment by bloerwald** [comment]
Does the keybind not work or is the option in the menu is checked? Is there any error in the log file?

**Comment by ihm-tswow** [comment]
Cannot reproduce on 3378, f9 works as intended on both custom and blizzard maps

**Comment by zarkeven** [comment]
> Does the keybind not work or is the option in the menu is checked? Is there any error in the log file?

the shortcut works, but the keybind does not. I restarted the program, attached is the log file when loading in and pressing the shortcut for it.

[log.txt](https://github.com/wowdev/noggit3/files/8027898/log.txt)


> Cannot reproduce on 3378, f9 works as intended on both custom and blizzard maps

That is the version I'm using.

**Comment by zarkeven** [comment]
update: seems that i had a macro in logitech's g-hub that starts another version of noggit. Sorry for the confusion.
