### ISSUE TITLE
A lot of maps are missing from selection (test-3379)

### ISSUE THREAD

**Issue by BlackMagicCoding** [wowdev/noggit3#119]
It seems that quite some maps are not available for selection - is this intentional?
I tried it with test-3370 and test-3379 downloaded from GitHub.
Love the application nonetheless - hits different being able to see all the maps without culling etc. :)
System: Windows 10 Home x64
WoW Client: 3.3.5a

== Classic ==
034 Stormwind Stockade
043 Wailing Caverns
048 Blackfathom Deeps
070 Uldaman
090 Gnomeregan
109 Sunken Temple
229 Blackrock Spire
230 Blackrock Depths
329 Stratholme
349 Maraudon
389 Ragefire Chasm
409 Molten Core
429 Dire Maul

== The Burning Crusade ==
540 Hellfire Citadel: The Shattered Halls
542 Hellfire Citadel: The Blood Furnace
544 Magtheridon's Lair
545 Coilfang: The Steamvault
546 Coilfang: The Underbog
547 Coilfang: The Slave Pens
548 Coilfang: Serpentshrine Cavern
550 Tempest Keep
552 Tempest Keep: The Arcatraz
553 Tempest Keep: The Botanica
554 Tempest Keep: The Mechanar
555 Auchindoun: Shadow Labyrinth
556 Auchindoun: Sethekk Halls
557 Auchindoun: Mana-Tombs
558 Auchindoun: Auchenai Crypts
565 Gruul's Lair

== Wrath of the Lich King ==
249 Onyxia's Lair
576 The Nexus

**Comment by bloerwald** [comment]
Yes, that’s intentional: noggit can’t edit them. WoW has two types of map: terrain based and a single object/collection  of models. Noggit can only edit terrain.

**Comment by BlackMagicCoding** [comment]
Oh that's unfortunate.
"Can't edit" means "can't show" as well I assume? For me it is showing them what is the most essential part.
Is there any other project to your knowledge which could fill the gap and handle the other map type?

**Comment by ihm-tswow** [comment]
wowmodelviewer can open (some) wmo files, wow blender studio can edit them. 

wow blender studio pushes its releases to this discord channel: https://discord.gg/SBEDRXrSnd

if you really want to make noggit display these wmo's,  you can try setting up your wowmodelviewer log path in the settings window, load the wmo in these maps and then spawn it into another map with noggit
