### ISSUE TITLE
broken adt texture shader for wdt flags ~0x4(?)

### ISSUE THREAD

**Issue by bloerwald** [wowdev/noggit3#61]
As reported by @Pursche (and as noted on wiki :(), pre-wotlk terrain -- so likely WDT flag 4 not set -- uses different blending for terrain textures. Instead of 

```c++
  return vec4 (t0 * (1.0 - (a0 + a1 + a2)) + t1 * a0 + t2 * a1 + t3 * a2, 1.0);
```
it is apparently
```c++
  vec4 color = t0;
  color = t1 * a0 + (color * (1.0 - a0));
  color = t2 * a1 + (color * (1.0 - a1));
  return t3 * a2 + (color * (1.0 - a2));
// = 
  return t3 * a2 + (t2 * a1 + (t1 * a0 + t0 * (1.0 - a0)) * (1.0 - a1)) * (1.0 - a2);
```

**Comment by Adspartan** [comment]
Noggit handle that correctly, the old data is converted to the newer format on loading and converted back when saving, this makes editing the textures much easier and the code is cleaner too.

This is the reason the shader only use the new format.
