### ISSUE TITLE
2d Rendering seems broken 

### ISSUE THREAD

**Issue by bloerwald** [wowdev/noggit3#63]
As per Kobiesan on discord, 2164 has broken lighting in 2d mode. They attached a “good” version and that version screenshot. 

It is unclear if the issue persists in more recent versions. If yes, it appears the normals are rotated to be facing downwards, likely mirrored not only on up axis though (mountain shadows are also wrong), and additionally slightly darker.

**Comment by bloerwald** [comment]
https://cdn.discordapp.com/attachments/715195034181304341/747245247461064864/unknown.png

https://cdn.discordapp.com/attachments/715195034181304341/747245668925571172/unknown.png

**Comment by Adspartan** [comment]
It seems to have been fixed at some point so I'm closing the issue
