### ISSUE TITLE
map_index: write MWMO even if it makes no sense so that emulators don’t fail 

### ISSUE THREAD

**Issue by bloerwald** [wowdev/noggit3#80]

**Comment by Warpten** [comment]
*sweats profusely*

**Comment by stoneharry** [comment]
Background: https://github.com/TrinityCore/TrinityCore/issues/26537

This will not fix historic maps, and saving them again in new versions of Noggit may break things. It seems like the fix should be on TC's side to me.

**Comment by stoneharry** [comment]
This can be closed because it was fixed in: https://github.com/TrinityCore/TrinityCore/commit/2d8d118c43531b5c15415bc6b3d9780f375cdfed
