### ISSUE TITLE
Script Brushes: The M2 model is not scaled when using add_m2()

### ISSUE THREAD

**Issue by gratural** [wowdev/noggit3#98]
The placed M2 model is always have scale size 1.0, until you enable the "Random scale" option in the Object Editor.
Tilt and rotate works fine without enabling any flags in the Object Editor panel.

**Comment by ihm-tswow** [comment]
fix: d019760a3653da18fae252a8986b6061c9eefab4

Thanks for the report! The function should now work regardless of object tool settings.
