### ISSUE TITLE
Script Brushes: The 'right_click' brush event never happens.

### ISSUE THREAD

**Issue by gratural** [wowdev/noggit3#99]
As far as I can tell, all the other events are working correctly.
Including holding and releasing the right button.
[0_test_tool.zip](https://github.com/wowdev/noggit3/files/6976149/0_test_tool.zip)

**Comment by ihm-tswow** [comment]
Fix: 29528b0d29dbdbc5f0e0233f278d39849a8f7828
Thanks for the report!
